## Element-wise Multiplication

$ \begin{bmatrix}
    0 & 0 & 0 & 0 \\
    1 & 1 & 1 & 1 \\
    2 & 2 & 2 & 2 \\
    3 & 3 & 3 & 3 \\
\end{bmatrix}  $ $ * 
 \begin{bmatrix}
    1 & 2 & 3 & 4 \\
\end{bmatrix} $ $ = \begin{bmatrix}
    0 & 0 & 0 & 0 \\
    1 & 1 & 1 & 1 \\
    2 & 2 & 2 & 2 \\
    3 & 3 & 3 & 3 \\
\end{bmatrix} * \begin{bmatrix}
    1 & 2 & 3 & 4 \\
    1 & 2 & 3 & 4 \\
    1 & 2 & 3 & 4 \\
    1 & 2 & 3 & 4 \\
\end{bmatrix} \longleftarrow BROADCASTING $

$ \begin{bmatrix}
    0 & 0 & 0 & 0 \\
    1 & 1 & 1 & 1 \\
    2 & 2 & 2 & 2 \\
    3 & 3 & 3 & 3 \\
\end{bmatrix}  $ $ * 
 \begin{bmatrix}
    6 \\
    7 \\
    8 \\
    9 \\
\end{bmatrix} $ $ = \begin{bmatrix}
    0 & 0 & 0 & 0 \\
    1 & 1 & 1 & 1 \\
    2 & 2 & 2 & 2 \\
    3 & 3 & 3 & 3 \\
\end{bmatrix} * \begin{bmatrix}
    6 & 6 & 6 & 6 \\
    7 & 7 & 7 & 7 \\
    8 & 8 & 8 & 8\\
    9 & 9 & 9 & 9\\
\end{bmatrix} \longleftarrow BROADCASTING $

$ \begin{bmatrix}
    1 & 2 & 3 & 4 \\
\end{bmatrix}  $ $ * 
 \begin{bmatrix}
    5 \\
    6 \\
    7 \\
    8 \\
\end{bmatrix} $ $ =  \quad BROADCASTING \longrightarrow  \begin{bmatrix}
    1 & 2 & 3 & 4 \\
    1 & 2 & 3 & 4 \\
    1 & 2 & 3 & 4 \\
    1 & 2 & 3 & 4 \\
\end{bmatrix} * \begin{bmatrix}
    5 & 5 & 5 & 5 \\
    6 & 6 & 6 & 6\\
    7 & 7 & 7 & 7\\ 
    8 & 8 & 8 & 8\\
\end{bmatrix} \longleftarrow BROADCASTING $

* Element-wise operations should occur ** on the same shape ** or broadcast compatible shapes (see prerequisite below)
* Order does not matter

### Prerequisite:  ###
$ A.shape = (A2, \quad A1) \longleftarrow A2 = lines, A1 = columns $   
$B.shape = (B2, \quad B1) \\ $

 $ (A2 = B2 \quad OR \quad (A2 = 1 \quad OR\quad B2 = 1)) $   
 
$ \quad\quad AND   $   

$(A1 = B1 \quad OR \quad (A1 = 1 \quad OR\quad B1 = 1)) $
### Output shape ###
$(max(A2, B2),\quad max(A1, B1))$

In [3]:
import numpy as np
A = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]) # (5,4) shape - 2 dimensions
B = np.array([1,2,3,4]) # (4,) shape - 1 dimension
B2d = np.array([[1,2,3,4]]) # (1, 4) shape - 2 dimensions
B_broadcasted = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]) # (5,4) shape - 2 dimensions

In [4]:
np.array([[1,2,3,4]])*np.array([[5],[6],[7],[8]])

array([[ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32]])

In [61]:
B * A

array([[ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [62]:
A * B_broadcasted

array([[ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [72]:
B2d * A

array([[ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

## Dot product

![title](http://www.thinkbiganalytics.com/wp-content/uploads/2015/11/smm2.jpg)

* Order does matter

### Prerequisite:  ###
$ A.shape = (A2, \quad A1) \longleftarrow A2 = lines, A1 = columns $   
$B.shape = (B2, \quad B1) \\ $
  
$ A1 = B2 $

### Output shape ###
$ (A2, B1) $

In [64]:
np.dot(A, B)

array([ 0, 10, 20, 30, 40])

In [65]:
np.dot(A, B2d) # error

ValueError: shapes (5,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [75]:
np.dot(B2d, A.T) # np.dot(A, B) == np.dot(B2d, A.T)

array([[ 0, 10, 20, 30, 40]])

In [76]:
np.dot(A, B2d.T)

array([[ 0],
       [10],
       [20],
       [30],
       [40]])